### ISSUE TITLE
I got BluetoothEnablePlugin.java uses or overrides a deprecated API on bluetooth_enable_fork 

### ISSUE THREAD

**Issue by haizad** [huitingyeong/bluetooth_enable#13]
Hi, I can't leave a comment on https://github.com/Alystrasz/bluetooth_enable_fork as it is a fork repository, so I posted here.

I used version 
bluetooth_enable_fork-0.1.5
bluetooth_enable_fork-0.1.6

Both got the same results. I don't know if you (@Alystrasz) read this, but that's current my issue.

Maybe this original repository got the same error, I am not quite sure. :)

**Update**

The issue might due to : 
1) the method BluetoothAdapter.getDefaultAdapter() used in the BluetoothEnablePlugin.java was deprecated in API level 31.
https://developer.android.com/reference/android/bluetooth/BluetoothAdapter#getDefaultAdapter()

2) Registrar in PluginRegistry has been deprecated
https://api.flutter.dev/javadoc/io/flutter/plugin/common/PluginRegistry.Registrar.html

**Comment by Alystrasz** [comment]
Hello, thanks for the report :)
How can I reproduce this warning message? I couldn't get it with the example app nor other applications using this package.
(I also thought I fixed this a long time ago, with commits from 159d19fe294b4af6332a1ff7b7dcc6e8e133375a to 68781699f9fdc42311efb908e44eefc77f9596fd)

**Comment by Alystrasz** [comment]
I was able to build a release of an application using this, so I suppose deprecation warnings don't prevent build.
https://github.com/Apolline-Lille/apolline-flutter/actions/runs/3530926513/jobs/5923473997

**Comment by ElHyperion** [comment]
This deprecation warning is still present, has there been any update on this? I use about 30 dependencies in my project and this is the only one to give me this warning, besides a vibration package.

If I create a PR for that, is there any chance it'll get released as a new version? I don't see any updates done on the fork for a year.

**Comment by Alystrasz** [comment]
> If I create a PR for that, is there any chance it'll get released as a new version? I don't see any updates done on the fork for a year.

I fixed that in #11, and that PR has been waiting for almost 2 years now :')

**Comment by huitingyeong** [comment]
Merged
